<?php
/**
 * list
 *
 * @copyright Copyright © 2018 PY Yick. All rights reserved.
 * @author    py.yick@cleargo.com
 */
?>
<?php $filelist = $block->processFilelist(); ?>
<div class="container">
    <form class="form form-download-csv" method="post" action="<?php echo $block->getDownloadLink(); ?>">
        <?php echo $this->getBlockHtml('formkey'); ?>
        <?php foreach ($filelist as $store_id => $list): ?>
            <div class="row">
                <div class="title-store"><?php echo $block->getStoreName($store_id); ?></div>
                <?php foreach ($list as $key => $items): ?>
                    <div class="title-type"><?php echo ucwords($key . ' Orders'); ?></div>
                    <select name="download-file-<?php echo $store_id . "-" . $key;?>" class="select select-csv">
                        <option value=""><?php echo __('Please Select'); ?></option>
                        <?php foreach ($items as $item): ?>
                            <option value="<?php echo $item; ?>"><?php echo $block->getFileLabel($item); ?></option>
                        <?php endforeach; ?>
                    </select>
                <?php endforeach; ?>
            </div>
        <?php endforeach; ?>
        <button class="action scalable primary" type="submit"><?php echo __('Download'); ?></button>
    </form>
</div>
