<?php
/**
 * list
 *
 * @copyright Copyright © 2018 PY Yick. All rights reserved.
 * @author    py.yick@cleargo.com
 */
?>
<?php $filelist = $block->processFilelist(); ?>
<div class="container">
    <?php foreach ($filelist as $store_id => $list): ?>
        <div class="row">
            <div class="title-store"><?php echo $block->getStoreName($store_id); ?></div>
            <?php foreach ($list as $key => $items): ?>
                <div class="title-type"><?php echo ucwords($key . ' Orders'); ?></div>
                <select class="select select-csv">
                    <option value=""><?php echo __('Please Select'); ?></option>
                    <?php foreach ($items as $item): ?>
                        <option value="<?php echo $item; ?>"><?php echo $block->getFileLabel($item); ?></option>
                    <?php endforeach; ?>
                </select>
            <?php endforeach; ?>
        </div>
    <?php endforeach; ?>
</div>
